<a href="https://colab.research.google.com/github/suryatejaganji/DATA-ANALYSIS-USING-PYTHON/blob/main/_Week_2_2_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd

# 1. Define a list of quarters
quarters = ['Q1', 'Q2', 'Q3']

# 2. Define a list of marketing platforms
marketing_platforms = ['Social Media', 'Email Marketing', 'Paid Ads']

# 3. Generate a 3x3 array of random integers between 100 and 1000
lead_data_array = np.random.randint(100, 1001, size=(len(quarters), len(marketing_platforms)))

print("Generated Lead Data Array:")
print(lead_data_array)

Generated Lead Data Array:
[[461 801 466]
 [621 758 213]
 [722 304 556]]


In [4]:
lead_generation_df = pd.DataFrame(lead_data_array, index=quarters, columns=marketing_platforms)
print("Lead Generation DataFrame:")
print(lead_generation_df)

Lead Generation DataFrame:
    Social Media  Email Marketing  Paid Ads
Q1           461              801       466
Q2           621              758       213
Q3           722              304       556


In [5]:
# 1. Generate a 3x3 array of random integers for cost per lead (e.g., between 50 and 500 INR)
cost_per_lead_array = np.random.randint(50, 501, size=(len(quarters), len(marketing_platforms)))

print("Generated Cost-per-Lead Array (INR):")
print(cost_per_lead_array)

# 2. Create the Cost-per-Lead DataFrame
cost_per_lead_df = pd.DataFrame(cost_per_lead_array, index=quarters, columns=marketing_platforms)

print("\nCost-per-Lead DataFrame (INR):")
print(cost_per_lead_df)

Generated Cost-per-Lead Array (INR):
[[363  70 424]
 [398  64 331]
 [267  52 198]]

Cost-per-Lead DataFrame (INR):
    Social Media  Email Marketing  Paid Ads
Q1           363               70       424
Q2           398               64       331
Q3           267               52       198


In [6]:
total_campaign_spend_df = lead_generation_df * cost_per_lead_df

print("\nTotal Campaign Spend DataFrame (INR):")
print(total_campaign_spend_df)


Total Campaign Spend DataFrame (INR):
    Social Media  Email Marketing  Paid Ads
Q1        167343            56070    197584
Q2        247158            48512     70503
Q3        192774            15808    110088


In [7]:
print("\nInformation about Total Campaign Spend DataFrame:")
total_campaign_spend_df.info()


Information about Total Campaign Spend DataFrame:
<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, Q1 to Q3
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Social Media     3 non-null      int64
 1   Email Marketing  3 non-null      int64
 2   Paid Ads         3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes


In [8]:
print("\nDescriptive Statistics for Total Campaign Spend DataFrame:")
total_campaign_spend_df.describe()


Descriptive Statistics for Total Campaign Spend DataFrame:


Social Media  Email Marketing       Paid Ads
count       3.000000         3.000000       3.000000
mean   202425.000000     40130.000000  126058.333333
std     40773.335736     21399.780466   65028.330752
min    167343.000000     15808.000000   70503.000000
25%    180058.500000     32160.000000   90295.500000
50%    192774.000000     48512.000000  110088.000000
75%    219966.000000     52291.000000  153836.000000
max    247158.000000     56070.000000  197584.000000

In [9]:
# 1. Simulate a 15% growth in lead generation for Q4
q4_lead_generation_df = lead_generation_df * 1.15

# 2. Update the index to reflect 'Q4' if we consider this as a single Q4 projection
# For simplicity, we are assuming this growth is applied across all previous quarters
# and then potentially representing a 'projected Q4' by taking average or sum of these inflated values.
# However, the prompt asks to 'increase the values in the original lead matrix by 15%',
# implying the structure remains similar but values are scaled.
# Let's create a DataFrame that represents the *projected* Q4 leads based on this growth.
# A more robust approach might be to add a new row for Q4, but the current instruction implies scaling existing data.

# Let's consider creating a Q4 specific row by averaging the Q1-Q3 values and then applying growth.
# Or, simpler, just illustrate the scaled 'original' matrix as the basis for Q4 thinking.
# Given the prompt, let's keep the scaled matrix, indicating what 'each quarter's leads would be like with 15% growth'.
# A more direct interpretation of 'simulate expected growth in lead generation for Q4' is to project new Q4 values.
# To align with the 'increase the values in the original lead matrix by 15%' and 'simulate expected growth in lead generation for Q4',
# I will create a new dataframe that has the same structure as the original but with inflated values,
# representing what *each quarter's* lead generation *would be* if it grew by 15% for Q4 consideration.

# Let's name it projected_q4_lead_generation_df to be clear that it's a projection.
projected_q4_lead_generation_df = lead_generation_df * 1.15

print("\nProjected Q4 Lead Generation DataFrame (15% Growth):")
print(projected_q4_lead_generation_df)



Projected Q4 Lead Generation DataFrame (15% Growth):
    Social Media  Email Marketing  Paid Ads
Q1        530.15           921.15    535.90
Q2        714.15           871.70    244.95
Q3        830.30           349.60    639.40


In [10]:
# Transpose the projected Q4 lead generation DataFrame
transposed_q4_projected_df = projected_q4_lead_generation_df.T

print("\nTransposed Q4 Projected Lead Generation DataFrame (Platforms as rows, Quarters as columns):")
print(transposed_q4_projected_df)



Transposed Q4 Projected Lead Generation DataFrame (Platforms as rows, Quarters as columns):
                     Q1      Q2     Q3
Social Media     530.15  714.15  830.3
Email Marketing  921.15  871.70  349.6
Paid Ads         535.90  244.95  639.4
