In [ ]:
import numpy as np

# 1. Revenue Matrix
revenue = np.array([
    [120000, 85000, 150000],   # Store A
    [135000, 90000, 160000],   # Store B
    [110000, 75000, 140000]    # Store C
])

# 2. Expenses Matrix
expenses = np.array([
    [70000, 50000, 90000],
    [80000, 60000, 95000],
    [65000, 48000, 88000]
])

# 3. Net Revenue
net_revenue = revenue - expenses
print("Net Revenue Matrix:\n", net_revenue)

# 4. Adjust for Inflation (8%)
inflation_factor = 1.08
adjusted_revenue = revenue * inflation_factor
print("\nInflation Adjusted Revenue:\n", adjusted_revenue)

# 5. Transpose
transposed = adjusted_revenue.T
print("\nTransposed Adjusted Matrix:\n", transposed)

# 6. Interpretation (optional computations)
store_totals = net_revenue.sum(axis=1)
category_totals = adjusted_revenue.sum(axis=0)

print("\nStore Profit Totals:", store_totals)
print("Category Revenue Totals (Adj):", category_totals)


Net Revenue Matrix:
 [[50000 35000 60000]
 [55000 30000 65000]
 [45000 27000 52000]]

Inflation Adjusted Revenue:
 [[129600.  91800. 162000.]
 [145800.  97200. 172800.]
 [118800.  81000. 151200.]]

Transposed Adjusted Matrix:
 [[129600. 145800. 118800.]
 [ 91800.  97200.  81000.]
 [162000. 172800. 151200.]]

Store Profit Totals: [145000 150000 124000]
Category Revenue Totals (Adj): [394200. 270000. 486000.]
