In [ ]:
import numpy as np

# 1. Lead Matrix
leads = np.array([
    [1200, 900, 1500],
    [1350, 950, 1600],
    [1400, 1000, 1700]
])

# 2. Cost-per-Lead Matrix
cpl = np.array([
    [15, 10, 25],
    [14, 11, 24],
    [16, 12, 26]
])

# 3. Total Marketing Cost
total_cost = leads * cpl
print("Total Marketing Cost:\n", total_cost)

# 4. Simulate Q4 Growth
growth_factor = 1.15
projected_q4 = leads * growth_factor
q4_row = projected_q4.mean(axis=0)

# Add Q4 to the matrix
full_leads = np.vstack([leads, q4_row])

# 5. Transpose
transposed = full_leads.T
print("\nTransposed Q1–Q4 Lead Matrix:\n", transposed)

# Optional Analysis
platform_totals = full_leads.sum(axis=0)
platform_growth = full_leads[:, -1] - full_leads[:, 0]


Total Marketing Cost:
 [[18000  9000 37500]
 [18900 10450 38400]
 [22400 12000 44200]]

Transposed Q1–Q4 Lead Matrix:
 [[1200.         1350.         1400.         1514.16666667]
 [ 900.          950.         1000.         1092.5       ]
 [1500.         1600.         1700.         1840.        ]]
